apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-two
spec:
  replicas: 3  # Pod say覺s覺n覺 3 olarak ayarlay覺n
  selector:
    matchLabels:
      app: service-two
  template:
    metadata:
      labels:
        app: service-two
    spec:
      containers:
      - name: service-two
        image: halitkalayci/servicetwo
        ports:
        - containerPort: 8081
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-two
spec:
  selector:
    app: service-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
